Importamos archivo csv "team_details"

In [2]:
import pandas as pd 
import numpy as np 

ruta_archivo_csv = r'C:\Users\Fernando\Desktop\CSV de NBA\archive\csv\team_details.csv'
df = pd.read_csv(ruta_archivo_csv)
df.head(50)
print(f'Cantidad de equipos: {len(df)}')

Cantidad de equipos: 25

Importamos csv de team_info_common

In [3]:
import pandas as pd 
import numpy as np 

ruta_archivo_csv = r'C:\Users\Fernando\Desktop\CSV de NBA\archive\csv\team_info_common.csv'
df = pd.read_csv(ruta_archivo_csv)
df.head(50)
print(f'Cantidad de equipos: {len(df)}')

Cantidad de equipos: 0

team_details

In [4]:
import pandas as pd 
import numpy as np 

ruta_archivo_csv = r'C:\Users\Fernando\Desktop\CSV de NBA\archive\csv\team_details.csv'
df = pd.read_csv(ruta_archivo_csv)

print(f'Cantidad de equipos: {len(df)}')

df.head(50)

Cantidad de equipos: 25

,team_id,abbreviation,nickname,yearfounded,city,arena,arenacapacity,owner,generalmanager,headcoach,dleagueaffiliation,facebook,instagram,twitter
0,1610612737,ATL,Hawks,1949.0,Atlanta,State Farm Arena,18729.0,Tony Ressler,Travis Schlenk,Quin Snyder,College Park Skyhawks,https://www.facebook.com/hawks,https://instagram.com/atlhawks,https://twitter.com/ATLHawks
1,1610612741,CHI,Bulls,1966.0,Chicago,United Center,21711.0,Michael Reinsdorf,Arturas Karnisovas,Billy Donovan,Windy City Bulls,https://www.facebook.com/chicagobulls,https://instagram.com/chicagobulls,https://twitter.com/chicagobulls
2,1610612742,DAL,Mavericks,1980.0,Dallas,American Airlines Center,19200.0,Mark Cuban,Nico Harrison,Jason Kidd,Texas Legends,https://www.facebook.com/dallasmavs,https://instagram.com/dallasmavs,https://twitter.com/dallasmavs
3,1610612743,DEN,Nuggets,1976.0,Denver,Ball Arena,NaN,Stan Kroenke,Calvin Booth,Michael Malone,Grand Rapids Gold,https://www.facebook.com/DenverNuggets,https://instagram.com/nuggets,https://twitter.com/nuggets
4,1610612744,GSW,Warriors,1946.0,Golden State,Chase Center,NaN,Joe Lacob,Bob Myers,Steve Kerr,Santa Cruz Warriors,https://www.facebook.com/warriors,https://instagram.com/warriors,https://twitter.com/warriors
5,1610612745,HOU,Rockets,1967.0,Houston,Toyota Center,18104.0,Tilman Fertitta,Rafael Stone,Ime Udoka,Rio Grande Valley Vipers,https://www.facebook.com/houstonrockets,https://instagram.com/houstonrockets,https://twitter.com/HoustonRockets
6,1610612746,LAC,Clippers,1970.0,Los Angeles,Crypto.com Arena,19060.0,Steve Ballmer,Michael Winger,Tyronn Lue,Agua Caliente Clippers of Ontario,https://www.facebook.com/LAClippers,https://instagram.com/laclippers,https://twitter.com/LAClippers
7,1610612747,LAL,Lakers,1948.0,Los Angeles,Crypto.com Arena,19060.0,Jeanie Buss,Rob Pelinka,Darvin Ham,South Bay Lakers,https://www.facebook.com/losangeleslakers,https://instagram.com/lakers,https://twitter.com/Lakers
8,1610612748,MIA,Heat,1988.0,Miami,Kaseya Center,19600.0,Micky Arison,Pat Riley,Erik Spoelstra,Sioux Falls Skyforce,https://www.facebook.com/MiamiHeat,https://instagram.com/miamiheat,https://twitter.com/MiamiHEAT
9,1610612749,MIL,Bucks,1968.0,Milwaukee,Fiserv Forum,17500.0,Wesley Edens &Â Marc Lasry,Jon Horst,Adrian Griffin,Wisconsin Herd,https://www.facebook.com/milwaukeebucks,https://instagram.com/bucks,https://twitter.com/Bucks
10,1610612750,MIN,Timberwolves,1989.0,Minnesota,Target Center,19356.0,Glen Taylor,Tim Connelly,Chris Finch,Iowa Wolves,https://www.facebook.com/MNTimberwolves,https://instagram.com/timberwolves,https://twitter.com/Timberwolves
11,1610612751,BKN,Nets,1976.0,Brooklyn,Barclays Center,NaN,Joe Tsai,Sean Marks,Jacque Vaughn,Long Island Nets,https://www.facebook.com/BrooklynNets,https://instagram.com/brooklynnets,https://twitter.com/BrooklynNets
12,1610612754,IND,Pacers,1976.0,Indiana,Gainbridge Fieldhouse,18345.0,Herb Simon,Kevin Pritchard,Rick Carlisle,Fort Wayne Mad Ants,https://www.facebook.com/pacers,https://instagram.com/pacers,https://twitter.com/Pacers
13,1610612755,PHI,76ers,1949.0,Philadelphia,Wells Fargo Center,NaN,Joshua Harris & David Blitzer,Elton Brand,Nick Nurse,Delaware Blue Coats,https://www.facebook.com/Sixers,https://instagram.com/sixers,https://twitter.com/Sixers
14,1610612756,PHX,Suns,1968.0,Phoenix,Footprint Center,NaN,Mat Ishbia,James Jones,Frank Vogel,No Affiliate,https://www.facebook.com/suns,https://instagram.com/suns,https://twitter.com/Suns
15,1610612757,POR,Trail Blazers,1970.0,Portland,Moda Center,19980.0,Jody Allen,Joe Cronin,Chauncey Billups,No Affiliate,https://www.facebook.com/trailblazers,https://instagram.com/trailblazers,https://twitter.com/trailblazers
16,1610612758,SAC,Kings,1948.0,Sacramento,Golden 1 Center,17500.0,Vivek Ranadive,Monte McNair,Mike Brown,Stockton Kings,https://www.facebook.com/sacramentokings,https://instagram.com/sacramentokings,https://twitter.com/SacramentoKings
17,1610612759,SAS,Spurs,1976.0,San Antonio,AT&T Center,18694.0,Peter Holt,Brian Wright,Gregg Popovich,Austin Spurs,https://www.facebook.com/Spurs,https://instagram.com/spurs,https://twitter.com/spurs
18,1610612760,OKC,Thunder,1967.0,Oklahoma City,Paycom Center,NaN,Clay Bennett,Sam Presti,Mark Daigneault,Oklahoma City Blue,https://www.facebook.com/OKCThunder,https://instagram.com/okcthunder,https://twitter.com/okcthunder
19,1610612761,TOR,Raptors,1995.0,Toronto,Scotiabank Arena,NaN,Lawrence Tanenbaum,Masai Ujiri,NaN,Raptors 905,https://www.facebook.com/TorontoRaptors,https://instagram.com/raptors,https://twitter.com/Raptors
20,1610612762,UTA,Jazz,1974.0,Utah,Delta Center,NaN,Ryan Smith,Justin Zanik,Will Hardy,Salt Lake City Stars,https://www.facebook.com/utahjazz,https://instagram.com/utahjazz,https://twitter.com/utahjazz
21,1610612763,MEM,Grizzlies,1995.0,Memphis,FedExForum,18119.0,Robert Pera,Zach Kleiman,Taylor Jenkins,Memphis Hustle,https://www.facebook.com/MemphisGrizzlies,https://instagram.com/memgrizz,https://twitter.com/memgrizz
22,1610612764,WAS,Wizards,1961.0,Washington,Capital One Arena,20647.0,Ted Leonsis,Tommy Sheppard,Wes Unseld,Capital City Go-Go,https://www.facebook.com/Wizards,https://instagram.com/washwizards,https://twitter.com/WashWizards
23,1610612765,DET,Pistons,1948.0,Detroit,Little Caesars Arena,NaN,Tom Gores,Ed Stefanski,Monty Williams,Motor City Cruise,https://www.facebook.com/detroitpistons,https://instagram.com/detroitpistons,https://twitter.com/DetroitPistons
24,1610612766,CHA,Hornets,1988.0,Charlotte,Spectrum Center,19026.0,Michael Jordan,Mitch Kupchak,Steve Clifford,Greensboro Swarm,https://www.facebook.com/hornets,https://instagram.com/hornets,https://twitter.com/hornets

Importacion de dataset juego, para filtrar por aÃ±o.

In [5]:
import pandas as pd 
import numpy as np 

ruta_archivo_csv = r'C:\Users\Fernando\Desktop\CSV de NBA\archive\csv\game.csv'
df_juego = pd.read_csv(ruta_archivo_csv)

print(f'Cantidad de equipos: {len(df_juego)}')

Cantidad de equipos: 65698

In [6]:
# Cargamos nuevamente el data set, para "parsear" la columna 'game_date'.
df_juego = pd.read_csv(ruta_archivo_csv, parse_dates=['game_date'])

# Convertimos al formato fecha.
# df_games['game_date'] = pd.to_datetime(df_games['game_date'])
df_juego['game_date'] = pd.to_datetime(df_juego['game_date'], format='%Y-%m-%d')

print(df_juego['game_date'].dtype)


# Filtrar por fechas:
games_filtred = df_juego[
    (df_juego['game_date'] >= '2010-10-03') & ## 2010-10-03
    (df_juego['game_date'] <= '2020-10-06') ## 2020-10-06
]

# obtener el set de 'game_id' vÃ¡lidos
df_juego_id_validados = set(games_filtred['game_id'])
print(f'Cantidad de partidos entre 2010 y 2020: {len(df_juego_id_validados)}')

# # Muestro los tipos de datos:
# for columna in df_juego_id_validados.columns:
#     print(columna)
#     print(df_juego_id_validados[columna].describe())
#     print('------------------------------------')

datetime64[ns]
Cantidad de partidos entre 2010 y 2020: 12285

In [7]:
games_filtred.to_csv(r'C:\Users\Fernando\Desktop\CSV de NBA\archive\csv\juego.csv', index=False)

# ___________________________________________________

Cargamos dataset 'juagadas'

In [ ]:
import pandas as pd 
import numpy as np 

ruta_archivo_csv = r'C:\Users\Fernando\Desktop\CSV de NBA\jugadas.csv'
df_jugadas = pd.read_csv(ruta_archivo_csv)

## Leemos solo la primer fila con el nombre de las columnas.
def obtener_nombre_columnas(ruta_archivo_csv):
    
    columnas = pd.read_csv(ruta_archivo_csv, nrows=0).columns.tolist()
    return columnas

primera_fila = obtener_nombre_columnas(ruta_archivo_csv)

# mostramos las columnas:
print("Columnas del archivo 'play_by_play': ")
for col in primera_fila:
    print("-", col)
print(f'Cantidad de equipos: {len(df_jugadas)}')

Columnas del archivo 'play_by_play':
- fecha_del_partido
- id_del_partido
- tipo_de_evento
- tipo_de_accion_evento
- periodo
- hora_de_acciÃ³n
- acciÃ³n_del_local
- acciÃ³n_neutral
- acciÃ³n_del_visitante
- id_jugador1
- nombre_jugador1
- id_equipo_jugador1
- id_jugador2
- nombre_jugador2
- id_equipo_jugador2
- id_jugador3
- nombre_jugador3
- id_equipo_jugador3
Cantidad de equipos: 4271334

EXPLORAMOS LA TABLA JUGADOR_DETALLE

In [14]:
## Definimos la ruta donde se encuentra
ruta_jugador_info = r'C:\Users\Fernando\Desktop\CSV de NBA\jugador detalle.csv' 

## Leemos el dataset
df = pd.read_csv(ruta_jugador_info)

# Muestro los tipos de datos:
for columna in df.columns:
    print(columna)
    print(df[columna].describe())
    print('------------------------------------')

person_id
count    4.171000e+03
mean     3.327509e+05
std      5.768886e+05
min      2.000000e+00
25%      7.612850e+04
50%      7.759300e+04
75%      2.022745e+05
max      1.631347e+06
Name: person_id, dtype: float64
------------------------------------
Nombre
count     4171
unique    1434
top       John
freq        77
Name: Nombre, dtype: object
------------------------------------
Apellido
count         4171
unique        2576
top       Williams
freq            67
Name: Apellido, dtype: object
------------------------------------
display_nombre_apellido
count               4171
unique              4139
top       George Johnson
freq                   3
Name: display_nombre_apellido, dtype: object
------------------------------------
Fecha_nacimiento
count              4171
unique             3895
top       04-04-05 0:00
freq                  3
Name: Fecha_nacimiento, dtype: object
------------------------------------
Pais
count     4170
unique      73
top        USA
freq      3770
Name: Pais, dtype: object
------------------------------------
height
count     4075
unique      27
top        6-7
freq       404
Name: height, dtype: object
------------------------------------
weight
count    4071.000000
mean      211.133382
std        26.926082
min       133.000000
25%       190.000000
50%       210.000000
75%       230.000000
max       360.000000
Name: weight, dtype: float64
------------------------------------
season_exp
count    4171.000000
mean        5.195157
std         4.470879
min         0.000000
25%         2.000000
50%         3.000000
75%         8.000000
max        22.000000
Name: season_exp, dtype: float64
------------------------------------
jersey
count     3191
unique     105
top         12
freq       125
Name: jersey, dtype: object
------------------------------------
position
count      4108
unique        7
top       Guard
freq       1604
Name: position, dtype: object
------------------------------------
rosterstatus
count         4171
unique           2
top       Inactive
freq          3740
Name: rosterstatus, dtype: object
------------------------------------
games_played_current_season_flag
count     4171
unique       1
top          N
freq      4171
Name: games_played_current_season_flag, dtype: object
------------------------------------
team_id
count    4.171000e+03
mean     1.339538e+09
std      6.026618e+08
min      0.000000e+00
25%      1.610613e+09
50%      1.610613e+09
75%      1.610613e+09
max      1.610613e+09
Name: team_id, dtype: float64
------------------------------------
from_year
count    4156.000000
mean     1989.303176
std        22.812298
min      1946.000000
25%      1974.000000
50%      1992.000000
75%      2010.000000
max      2022.000000
Name: from_year, dtype: float64
------------------------------------
to_year
count    4156.000000
mean     1993.746631
std        23.636712
min      1946.000000
25%      1977.000000
50%      1998.000000
75%      2015.000000
max      2023.000000
Name: to_year, dtype: float64
------------------------------------

In [16]:
## Leemos solo la primer fila con el nombre de las columnas.
def obtener_nombre_columnas(ruta_jugador_info):
    
    columnas = pd.read_csv(ruta_jugador_info, nrows=0).columns.tolist()
    return columnas

primera_fila = obtener_nombre_columnas(ruta_jugador_info)
# mostramos las columnas:
print("Columnas del archivo 'jugador deatalle': ")
for col in primera_fila:
    print("-", col)

Columnas del archivo 'jugador deatalle':
- person_id
- Nombre
- Apellido
- display_nombre_apellido
- Fecha_nacimiento
- Pais
- height
- weight
- season_exp
- jersey
- position
- rosterstatus
- games_played_current_season_flag
- team_id
- from_year
- to_year

Parseamos DATASET para formato FECHA

In [18]:
# Cargamos nuevamente el data set, para "parsear" la columna 'game_date'.
df = pd.read_csv(ruta_jugador_info, parse_dates=['Fecha_nacimiento'])

# Convertimos al formato fecha.
# df_games['game_date'] = pd.to_datetime(df_games['game_date'])
df['Fecha_nacimiento'] = pd.to_datetime(df['Fecha_nacimiento'], format='%Y-%m-%d')

print(df['Fecha_nacimiento'].dtype)

# Muestro los tipos de datos:
for columna in df.columns:
    print(columna)
    print(df[columna].describe())
    print('------------------------------------')

C:\Users\Fernando\AppData\Local\Temp\ipykernel_7236\2759324688.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv(ruta_jugador_info, parse_dates=['Fecha_nacimiento'])

datetime64[ns]
person_id
count    4.171000e+03
mean     3.327509e+05
std      5.768886e+05
min      2.000000e+00
25%      7.612850e+04
50%      7.759300e+04
75%      2.022745e+05
max      1.631347e+06
Name: person_id, dtype: float64
------------------------------------
Nombre
count     4171
unique    1434
top       John
freq        77
Name: Nombre, dtype: object
------------------------------------
Apellido
count         4171
unique        2576
top       Williams
freq            67
Name: Apellido, dtype: object
------------------------------------
display_nombre_apellido
count               4171
unique              4139
top       George Johnson
freq                   3
Name: display_nombre_apellido, dtype: object
------------------------------------
Fecha_nacimiento
count                             4171
mean     2024-09-14 20:07:18.456005632
min                1975-01-01 00:00:00
25%                1992-06-26 12:00:00
50%                2025-10-22 00:00:00
75%                2057-01-07 00:00:00
max                2074-12-29 00:00:00
Name: Fecha_nacimiento, dtype: object
------------------------------------
Pais
count     4170
unique      73
top        USA
freq      3770
Name: Pais, dtype: object
------------------------------------
height
count     4075
unique      27
top        6-7
freq       404
Name: height, dtype: object
------------------------------------
weight
count    4071.000000
mean      211.133382
std        26.926082
min       133.000000
25%       190.000000
50%       210.000000
75%       230.000000
max       360.000000
Name: weight, dtype: float64
------------------------------------
season_exp
count    4171.000000
mean        5.195157
std         4.470879
min         0.000000
25%         2.000000
50%         3.000000
75%         8.000000
max        22.000000
Name: season_exp, dtype: float64
------------------------------------
jersey
count     3191
unique     105
top         12
freq       125
Name: jersey, dtype: object
------------------------------------
position
count      4108
unique        7
top       Guard
freq       1604
Name: position, dtype: object
------------------------------------
rosterstatus
count         4171
unique           2
top       Inactive
freq          3740
Name: rosterstatus, dtype: object
------------------------------------
games_played_current_season_flag
count     4171
unique       1
top          N
freq      4171
Name: games_played_current_season_flag, dtype: object
------------------------------------
team_id
count    4.171000e+03
mean     1.339538e+09
std      6.026618e+08
min      0.000000e+00
25%      1.610613e+09
50%      1.610613e+09
75%      1.610613e+09
max      1.610613e+09
Name: team_id, dtype: float64
------------------------------------
from_year
count    4156.000000
mean     1989.303176
std        22.812298
min      1946.000000
25%      1974.000000
50%      1992.000000
75%      2010.000000
max      2022.000000
Name: from_year, dtype: float64
------------------------------------
to_year
count    4156.000000
mean     1993.746631
std        23.636712
min      1946.000000
25%      1977.000000
50%      1998.000000
75%      2015.000000
max      2023.000000
Name: to_year, dtype: float64
------------------------------------

Cantidad de filas con team_id

In [19]:
import pandas as pd

# 1. Mostrar los jugadores con team_id = 0
jugadores_team_id_0 = df[df['team_id'] == 0]
print("ð¯ Filas con team_id = 0:")
print(jugadores_team_id_0)

ð¯ Filas con team_id = 0:
      person_id   Nombre   Apellido display_nombre_apellido Fecha_nacimiento  \
7        203518     Alex    Abrines            Alex Abrines       1993-01-08
13       203112   Quincy        Acy              Quincy Acy       1990-06-10
16       200801   Hassan      Adams            Hassan Adams       1984-06-20
17      1629121   Jaylen      Adams            Jaylen Adams       1996-04-05
25       202399     Jeff     Adrien             Jeff Adrien       1986-10-02
...         ...      ...        ...                     ...              ...
4148     201156     Nick      Young              Nick Young       1985-01-06
4159     202545     Luke     Zeller             Luke Zeller       1987-07-04
4162       1917     Wang    Zhi-zhi            Wang Zhi-zhi       1977-08-07
4163        678   George      Zidek            George Zidek       2073-02-08
4164       2583  Derrick  Zimmerman       Derrick Zimmerman       1981-02-12

       Pais height  weight  season_exp jersey        position rosterstatus  \
7     Spain    6-6   200.0           3    NaN           Guard     Inactive
13      USA    6-7   240.0           7    NaN         Forward     Inactive
16      USA    6-4   220.0           2    NaN         Forward     Inactive
17      USA    6-0   225.0           3    NaN           Guard     Inactive
25      USA    NaN     NaN           6    NaN             NaN     Inactive
...     ...    ...     ...         ...    ...             ...          ...
4148    USA    6-7   210.0          12    NaN   Guard-Forward     Inactive
4159    USA   6-11   245.0           1    NaN  Forward-Center     Inactive
4162  China    7-1   284.0           6    NaN          Center     Inactive
4163    USA    7-0   250.0           3    NaN          Center     Inactive
4164    USA    6-3   195.0           1    NaN           Guard     Inactive

     games_played_current_season_flag  team_id  from_year  to_year
7                                   N        0     2016.0   2018.0
13                                  N        0     2012.0   2018.0
16                                  N        0     2006.0   2008.0
17                                  N        0     2018.0   2020.0
25                                  N        0     2010.0   2014.0
...                               ...      ...        ...      ...
4148                                N        0     2007.0   2018.0
4159                                N        0     2012.0   2012.0
4162                                N        0     2000.0   2004.0
4163                                N        0     1995.0   1997.0
4164                                N        0     2005.0   2005.0

[702 rows x 16 columns]

In [20]:
# Filtrar jugadores con team_id = 0
jugadores_team_id_0 = df[df['team_id'] == 0]

# Mostrar cantidad
cantidad = jugadores_team_id_0.shape[0]
print(f"ð¢ Cantidad de jugadores con team_id = 0: {cantidad}")

ð¢ Cantidad de jugadores con team_id = 0: 702

Analisis de cuantas fechas de nacimiento hay superiores al aÃ±o 2000

In [23]:
# Filtrar por fechas posteriores a 2000-01-01
jugadores_2000 = df[df['Fecha_nacimiento'] > pd.Timestamp("2000-01-01")]
# Ordenar las fechas de menor a mayor
jugadores_2000 = jugadores_2000.sort_values(by='Fecha_nacimiento', ascending=True)

# Mostrar resultados
print("ð Jugadores nacidos despuÃ©s del 01-01-2000:")
print(jugadores_2000)

# Mostrar cuÃ¡ntos hay
print(f"\nð¢ Total de jugadores nacidos despuÃ©s del 2000: {jugadores_2000.shape[0]}")

ð Jugadores nacidos despuÃ©s del 01-01-2000:
      person_id  Nombre    Apellido display_nombre_apellido Fecha_nacimiento  \
959     1630245     Ayo     Dosunmu             Ayo Dosunmu       2000-01-17
275     1631262   Jules     Bernard           Jules Bernard       2000-01-21
1261    1629636  Darius     Garland          Darius Garland       2000-01-26
3933    1629632    Coby       White              Coby White       2000-02-16
1467    1630169  Tyrese  Haliburton       Tyrese Haliburton       2000-02-29
...         ...     ...         ...                     ...              ...
2920       2130    Mike   Penberthy          Mike Penberthy       2074-11-29
600         713   Chris        Carr              Chris Carr       2074-12-03
2062        954   Kerry     Kittles           Kerry Kittles       2074-12-06
2252       1732  Felipe       Lopez            Felipe Lopez       2074-12-19
3351       1852    Jeff    Sheppard           Jeff Sheppard       2074-12-29

                    Pais height  weight  season_exp jersey       position  \
959                  USA    6-5   200.0           2     12          Guard
275                  USA    NaN     NaN           0    NaN            NaN
1261                 USA    6-1   192.0           4     10          Guard
3933                 USA    6-5   195.0           4      0          Guard
1467                 USA    6-5   185.0           3      0          Guard
...                  ...    ...     ...         ...    ...            ...
2920                 USA    6-3   180.0           2    NaN            NaN
600                  USA    6-6   220.0           7    NaN          Guard
2062                 USA    6-5   185.0           9    NaN          Guard
2252  Dominican Republic    6-5   195.0           5     13  Guard-Forward
3351                 USA    6-3   190.0           1    NaN          Guard

     rosterstatus games_played_current_season_flag     team_id  from_year  \
959        Active                                N  1610612741     2021.0
275      Inactive                                N           0        NaN
1261       Active                                N  1610612739     2019.0
3933       Active                                N  1610612741     2019.0
1467       Active                                N  1610612754     2020.0
...           ...                              ...         ...        ...
2920     Inactive                                N           0     2000.0
600      Inactive                                N           0     1995.0
2062     Inactive                                N           0     1996.0
2252     Inactive                                N  1610612763     1998.0
3351     Inactive                                N           0     1998.0

      to_year
959    2023.0
275       NaN
1261   2023.0
3933   2023.0
1467   2023.0
...       ...
2920   2001.0
600    2000.0
2062   2004.0
2252   2002.0
3351   1998.0

[2545 rows x 16 columns]

ð¢ Total de jugadores nacidos despuÃ©s del 2000: 2545

Empezamos a filtrar y borrar

In [32]:
# Cargamos nuevamente el data set, para "parsear" la columna 'game_date'.
df = pd.read_csv(ruta_jugador_info, parse_dates=['Fecha_nacimiento'])

# Convertimos al formato fecha.
# df_games['game_date'] = pd.to_datetime(df_games['game_date'])
df['Fecha_nacimiento'] = pd.to_datetime(df['Fecha_nacimiento'], format='%Y-%m-%d')

# Asegurarse de que 'to_year' sea numÃ©rico (por si viene como texto)
df['to_year'] = pd.to_numeric(df['to_year'], errors='coerce')

# Filtrar las filas donde to_year estÃ© entre 2010 y 2020 (inclusive)
df = df[(df['to_year'] >= 2010) & (df['to_year'] <= 2020)]

# Mostrar resultados
print("ð Jugadores con to_year entre 2010 y 2020:")
print(df[['display_nombre_apellido', 'to_year']])

# Cantidad total
print(f"\nð¢ Total: {df.shape[0]}")

# Guardamos
df.to_csv(r'C:\Users\Fernando\Desktop\CSV de NBA\jugador detalle.csv')

C:\Users\Fernando\AppData\Local\Temp\ipykernel_7236\16077218.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv(ruta_jugador_info, parse_dates=['Fecha_nacimiento'])

ð Jugadores con to_year entre 2010 y 2020:
     display_nombre_apellido  to_year
7               Alex Abrines   2018.0
13                Quincy Acy   2018.0
17              Jaylen Adams   2020.0
18              Jordan Adams   2015.0
23                 Deng Adel   2018.0
...                      ...      ...
4150               Sam Young   2012.0
4159             Luke Zeller   2012.0
4165       Stephen Zimmerman   2016.0
4166             Paul Zipser   2017.0
4167              Ante Zizic   2019.0

[783 rows x 2 columns]

ð¢ Total: 783

Filtrmos si la posicion del juador es 0., si es asÃ­ la borramos

In [34]:
## Definimos la ruta donde se encuentra
ruta_jugador_info = r'C:\Users\Fernando\Desktop\CSV de NBA\jugador detalle.csv' 

## Leemos el dataset
df = pd.read_csv(ruta_jugador_info)

# Eliminar filas donde la columna 'position' tiene valores nulos
df = df.dropna(subset=['position'])

# Verificar cuÃ¡ntas filas quedaron
print(f"â Total de filas luego de eliminar posiciones nulas: {df.shape[0]}")


# Guardamos 
df.to_csv(r'C:\Users\Fernando\Desktop\CSV de NBA\jugador detalle.csv')

â Total de filas luego de eliminar posiciones nulas: 766

Eliminamos las filas en donde la columna 'team_id' tiene valores igual a 0. NO GUARDAR TODAVÃA

In [3]:
import pandas as pd 
import numpy as np 

## Definimos la ruta donde se encuentra
ruta_jugador_info = r'C:\Users\Fernando\Desktop\CSV de NBA\jugador detalle.csv' 

## Leemos el dataset
df = pd.read_csv(ruta_jugador_info)

# Eliminar filas donde 'team_id' es igual a 0
df = df[df['id_equipo'] != 0]

# Verificar cuÃ¡ntas filas quedaron
print(f"â Total de filas luego de eliminar id_equipo = 0: {df.shape[0]}")
df.to_csv(r'C:\Users\Fernando\Desktop\CSV de NBA\jugador detalle.csv')

â Total de filas luego de eliminar id_equipo = 0: 530

In [ ]:
import pandas as pd 
import numpy as np 

## Definimos la ruta donde se encuentra
ruta_jugador_info = r'C:\Users\Fernando\Desktop\CSV de NBA\jugador detalle.xlsx' 

## Leemos el dataset
df_fil = pd.read_excel(ruta_jugador_info)

df_fil.to_csv(r'C:\Users\Fernando\Desktop\CSV de NBA\jugador detalle.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Fernando\\Desktop\\CSV de NBA\\jugador detalle.xlsx'

In [9]:
import pandas as pd 
import numpy as np 

## Definimos la ruta donde se encuentra
ruta_jugador_info = r'C:\Users\Fernando\Desktop\CSV de NBA\jugador detalle.csv' 

## Leemos el dataset
df = pd.read_csv(ruta_jugador_info)

# Eliminar columnas innecesarias
columnas_a_eliminar = ['Unnamed: 0.4', 'Unnamed: 0.3', 'Unnamed: 0.2', 'Unnamed: 0.1', 'Unnamed: 0']
df = df.drop(columns=columnas_a_eliminar, errors='ignore')

def convertir_pies_a_cm(valor):
    try:
        # Separar en pies y pulgadas
        pies, pulgadas = str(valor).split("-")
        pies = int(pies)
        pulgadas = int(pulgadas)
        # Convertir a centÃ­metros
        altura_cm = pies * 30.48 + pulgadas * 2.54
        return round(altura_cm, 2)
    except:
        return None

df['Altura'] = df['Altura'].apply(convertir_pies_a_cm)

# FechaNacimiento: convertir a datetime
df['FechaNacimiento'] = pd.to_datetime(df['FechaNacimiento'], errors='coerce')

# JugoEstaTemporada: convertir a booleano (N = False, Y = True)
df['JugoEstaTemporada'] = df['JugoEstaTemporada'].map({'Y': True, 'N': False})


print(df)

     IDJugador   Nombre   Apellido DisplaNombreApellido FechaNacimiento  \
0       203919   Jordan      Adams         Jordan Adams      1994-08-07
1      1629061     Deng       Adel            Deng Adel      1997-01-02
2       201167    Arron    Afflalo        Arron Afflalo      1985-10-15
3       201336    Blake     Ahearn         Blake Ahearn      1984-05-27
4       201582   Alexis     Ajinca        Alexis Ajinca      1988-06-05
..         ...      ...        ...                  ...             ...
525    1626202      Joe      Young            Joe Young      1992-06-27
526     201970      Sam      Young            Sam Young      1985-01-06
527    1627757  Stephen  Zimmerman    Stephen Zimmerman      1996-09-09
528    1627835     Paul     Zipser          Paul Zipser      1994-02-18
529    1627790     Ante      Zizic           Ante Zizic      1997-04-01

            Pais  Altura  Peso  TemporadasExperiencia  NroCamiseta  \
0            USA     NaN   209                      3          3.0
1    South Sudan     NaN   200                      2         32.0
2            USA     NaN   210                     12          4.0
3            USA     NaN   190                      4          2.0
4         France     NaN   248                      8         42.0
..           ...     ...   ...                    ...          ...
525          USA     NaN   185                      3          3.0
526          USA     NaN   225                      5          4.0
527          USA  213.36   240                      2         33.0
528      Germany     NaN   226                      2         16.0
529      Croatia     NaN   266                      4         41.0

          Posicion EstadoPlantel  JugoEstaTemporada    IDEquipo  DesdeAÃ±o  \
0            Guard      Inactive              False  1610612763      2014
1          Forward      Inactive              False  1610612739      2018
2            Guard      Inactive              False  1610612743      2007
3            Guard      Inactive              False  1610612748      2007
4           Center      Inactive              False  1610612740      2008
..             ...           ...                ...         ...       ...
525          Guard      Inactive              False  1610612754      2015
526  Forward-Guard      Inactive              False  1610612763      2009
527         Center      Inactive              False  1610612753      2016
528        Forward      Inactive              False  1610612741      2016
529         Center      Inactive              False  1610612739      2017

     HastaAÃ±o
0        2015
1        2018
2        2017
3        2011
4        2017
..        ...
525      2017
526      2012
527      2016
528      2017
529      2019

[530 rows x 16 columns]